services:
  delivery-service-mock:
    image: "sheyenrath/wiremock.net"
    ports:
      - "9091:80"
  database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=TestPassword1!"
    ports:
      - "1433:1433"
  service-bus-emulator:
    image: devopsifyme/sbemu:latest
    environment:
      - EMULATOR__RABBITMQ__HOST=rabbit
      - EMULATOR__RABBITMQ__USERNAME=guest
      - EMULATOR__RABBITMQ__PASSWORD=guest
    ports:
      - "5671:5671"
    links: 
      - rabbit
    depends_on:
      rabbit:
        condition: service_healthy
  rabbit:
    image: rabbitmq:3-management
    command: ["bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server"]
    ports:
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 30s
      retries: 60